language: shell
os: linux

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - sudo bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh )
