language: shell
os: linux
sudo: required

matrix:
  include:
    - dist: bionic
    #- dist: xenial

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - sudo apt-get remove --purge mysql* -y
  - wget https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh 
  - chmod +x wpimgsetup.sh 
  - bash wpimgsetup.sh
  - wget https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Cloud-init/per-instance.sh
  - chmod +x wpimgsetup.sh 
  - bash wpimgsetup.sh 
