language: shell
os: linux

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - sudo apt-get remove --purge mysql* -y
  - wget https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh 
  - sudo chmod +x wpimgsetup.sh 
  - sudo bash -x wpimgsetup.sh


