language: shell
os: linux

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        echo 'Install WP'
        bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh )
        echo 'Per Instance'
        #bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Cloud-init/per-instance.sh )
    fi 