language: shell
os: linux

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - wget https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh && chmod +x wpimgsetup.sh && bash wpimgsetup.sh
